### ISSUE TITLE
LoopiaAPI changed

### ISSUE THREAD

**Issue by rogerthn2019** [runfalk/certbot-dns-loopia#14]
From Loopia mail 2022-02-11
`Den 23 februari 2022 kommer vi att uppgradera våra servrar och förbättra LoopiaAPI`
Translated by Google
`On February 23, 2022, we will upgrade our servers and improve LoopiaAPI`
Will there be any update of the excellent certbot-dns-loopia?
addZoneRecord XML response:
`<?xml version="1.0" encoding="UTF-8"?>
<methodResponse><fault><value><struct><member><name>faultCode</name><value><int>623</int></value></member><member><name>faultString</name><value><string>Calling parameters do not match signature</string></value></member></struct></value></fault></methodResponse>`

PS
Sorry, I'm not using this but it would be great if if could with the new LoopiaAPI

**Comment by runfalk** [comment]
I'm no longer a Loopia customer and have no means of testing this, but if someone makes a PR I'm happy to accept it and release a new version.

**Comment by rogerthn2019** [comment]
Response from Loopia, customer_number is now mandatory

**Comment by kmpm** [comment]
I am still a customer and planning spend some time on this issue during upcoming weekend.

**Comment by kmpm** [comment]
@rogerthn2019, is it possible that you are using a reseller account?
Being a reseller is the only time that customer_number should be used, according to the documentation https://www.loopia.se/api/addzonerecord/

I do not have a reseller account so that I can verify it's functionality but I'll try to add it anyway.

**Comment by rogerthn2019** [comment]
@kmpm I'm not using a reseller account and I did ask for the old API specification to maybe enable an update to the code.
After the response below from Loopia Secondline Support I did reply that they need to update documentation.
`Hej!

Gamla dokumentationen bör inte behövas då callsen är väldigt lika som de vi har nu, API-sidan hos oss har ej ändrats sen uppdateringen.

Det som ska vara med bör vara följande: addZoneRecord(username, password, [customer_number,] domain, subdomain, record_obj)

Kundnummer är ett krav numera för att det skall fungera, har du blockat din inloggning till kundzonen genom att slå på "Endast BankID" så behöver det slås av.`

**Comment by kmpm** [comment]
@rogerthn2019, strange. It just worked for me without any changes but as I said, will give it a proper look this weekend.

**Comment by rogerthn2019** [comment]
@kmpm I did think that I was using certbot-dns-loopia but as said above, I do not but maybe I should.
certbot-loopiadns did stop to behave after the Loopia update, I've tried to add customer number but still error `623	Calling parameters do not match signature.`

**Comment by kmpm** [comment]
Do you have a link to the `certbot-loopiadns` project?

**Comment by rogerthn2019** [comment]
Yes, I've tried to add comments but still not accepted
https://techblog.se/2020/01/19/automating-certbot-dns-validation-with-loopiadns-lets-encrypt/

**Comment by rogerthn2019** [comment]
Looks like Loopia Secondline Support can't be "trusted" 👎 
certbot-dns-loopia is working as is 🥇 
Hence, no need to add customer_number and there must be something else that has changed to "disable" certbot-loopiadns

**Comment by gabbe** [comment]
Something changed yesterday evening with the API, and now authentication seems to be working again. All my tests that failed yesterday magically works this morning so maybe there is no need to update certbot-dns-loopia.

**Comment by kmpm** [comment]
Closing this specific issue but made a new enhancement issue #15  out of it.
