### ISSUE TITLE
Move version history out of README and into Releases

### ISSUE THREAD

**Issue by MrRawbin** [runfalk/certbot-dns-loopia#33]
The version history bloats the README file. The version history should be located under the `Releases` tab in GitHub instead.

**Comment by kmpm** [comment]
Added the v1.0.0 and v1.0.1 to releases.
Older ones have no tags.

**Comment by MrRawbin** [comment]
Very nice! Do you think that we can sacrifice the older ones from the README as well then? I am guessing they don't serve much of a purpose nowadays anyway.

**Comment by MrRawbin** [comment]
I am making some changes to the README file anyway, so I can drop them from there while I am at it.
